---
version: '2'
services:
  db:
    image: postgres
    network_mode: host
    environment:
    - POSTGRES_USER=pulp
    - POSTGRES_PASSWORD=pulp
    volumes:
    - ./.volume/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    network_mode: host
  api:
    image: evanshawn/pulp-api
    network_mode: host
    env_file: .env
    command: [--dogstatsd-tags=$$HOSTNAME]
    depends_on:
    - db
    - redis
    volumes:
    - ./.volume/pulp:/var/lib/pulp
  content:
    image: evanshawn/pulp-content
    network_mode: host
    env_file: .env
    depends_on:
    - db
    - api
    volumes:
    - ./.volume/pulp:/var/lib/pulp
  resource-manager:
    image: evanshawn/pulp-resource-manager
    network_mode: host
    env_file: .env
    depends_on:
    - db
    - api
    - redis
    volumes:
    - ./.volume/pulp:/var/lib/pulp
  worker:
    image: evanshawn/pulp-worker
    network_mode: host
    env_file: .env
    depends_on:
    - db
    - api
    - redis
    volumes:
    - ./.volume/pulp:/var/lib/pulp
