---
name: Auto Actions

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [labeled, unlabeled, synchronize, review_requested, opened, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve-github-actions:
    runs-on: ubuntu-latest
    if: >-
      github.actor == 'dependabot[bot]'
      ||
      github.actor == 'dependabot-preview[bot]'
    steps:
    - uses: hmarr/auto-approve-action@v3.1.0
      if: >-
        contains( github.event.pull_request.labels.*.name, 'github_actions')
        ||
        (
          contains( github.event.pull_request.labels.*.name, 'dependencies')
          &&
          ! contains( github.event.pull_request.labels.*.name, 'core_pulp_modules')
        )
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    name: Enable automerge on jobs with relevant labels
    runs-on: ubuntu-latest
    steps:
    - name: Enable auto-merge
      if: >-
        contains( github.event.pull_request.labels.*.name, 'github_actions')
        ||
        contains( github.event.pull_request.labels.*.name, 'automerge')
        ||
        (
          contains( github.event.pull_request.labels.*.name, 'dependencies')
          &&
          ! contains( github.event.pull_request.labels.*.name, 'core_pulp_modules')
        )
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
