---
name: Remove old artifacts

on:  # yamllint disable-line rule:truthy
  # Every day at 1am
  schedule:
  - cron: 0 1 * * *

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: 1 month
        # Optional inputs
        # skip-tags: true
        skip-recent: 3
